on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    outputs:
      badges: "./badge-*.svg"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run test:ci
      - run: |
          npm install jest-coverage-badges
          npx jest-coverage-badges input "./.coverage/coverage-summary.json" output "."  