on: [push]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            **/node_modules

      - name: Install dependencies
        run: npm install
        
  run_coverage_tests:
    needs:
      - install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Run coverage tests
        run: npm run test:ci
                  
  create_badges:
    needs:
      - run_coverage_tests
    runs-on: ubuntu-latest
    steps:
      - run: npm install jest-coverage-badges

      - name: building coverage badges
        run: npx jest-coverage-badges input "./.coverage/coverage-summary.json" output "./.public"  

      - name: commiting badges
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add ./.public/badge-*.svg
          if [-z "$(git status --porcelain)"]; then
            echo "::set-output name=push::false"
          else
            git commit -m "Add changes" -a
            echo "::set-output name=push::true"
          fi
        shell: bash
      - name: push badges
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}