on: [push]

jobs:
  run_tests_and_create_badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        
      - name: install dependencies
        run: npm install

      - name: run linter
        run: npm run lint

      - name: run coverage tests
        run: npm run test:ci
